### ISSUE TITLE
A question on the implementation of Jacobi basis

### ISSUE THREAD

**Issue by TaoLbr1993** [GraphPKU/JacobiConv#1]
Dear authors, 

Thanks for sharing the code of the excellent work JacobiConv.
Recently, I try to re-implement the model and met a question on the implementation of JacobiConv.

The recurrence relations of Jacobi polynomials have the form 
$$P_n(L) = A_n * L * P_{n-1}(L) + B_n * P_{n-1}(L) + C_n * P_{n-2}(L)$$
 where $B_n = \frac{a^2-b^2}{2n(n+a+b)(2n+a+b-2)}$.
However, I notice that in line 148 of the file impl/PolyConv.py, the variable ```tmp2_2```, which in my opinion represents $B_n$, has a negative before it.
I wonder if this is my misunderstanding on the implementation, or just a mistake in the code?

Very thanks for your attention and reply!

**Comment by Xi-yuanWang** [comment]
Dear TaoLbr1993,

Sorry for my late reply. It may be a mistake. However, you can simply consider the `a` parameter as beta of Jacobi polynomials and the `b` parameter as alpha, then the implementation is right. 

Sincerely,
Xiyuan Wang
